# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jgMxR3JWpQagCpSRZuR_aGTE451HXG9S
"""

import streamlit as st

from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

st.set_page_config(
    page_title="Assistant Tarifaire",
    layout="wide"
)

st.title("💰 Assistant Guide Tarifaire")

@st.cache_resource
def load_db():

    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )

    db = FAISS.load_local(
        "vectorstore",
        embeddings,
        allow_dangerous_deserialization=True
    )

    return db

db = load_db()

question = st.text_input(
    "Posez votre question"
)

if question:

    docs = db.similarity_search(
        question,
        k=3
    )

    st.subheader("Réponse")

    st.write(docs[0].page_content)

    st.subheader("Autres passages pertinents")

    for i, doc in enumerate(docs):

        st.markdown(f"### Passage {i+1}")

        st.write(doc.page_content)